name: Deploy Yii2 App to EC2 via Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./myapp
          file: ./myapp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker service rm yii2-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
            docker service create \
              --name yii2-app \
              --publish 8080:80 \
              ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

